config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
  controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :users do
    resources :badges, only: %i[index]
    resources :feedbacks, only: %i[new create]
  end

  resources :tests_users, only: %i[show update] do
    resources :gists, only: :create
    member do
      get :attempt
    end
  end

  namespace :admin do
    resources :badges
    resources :gists, only: %i[index destroy]
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/badge.rb
# frozen_string_literal: true

class Badge < ApplicationRecord

  enum badges_rules: {
    all_tests_by_category: 0,
    pass_test_by_level: 1,
    first_test_passed: 2
  }

  has_many :badges_users, dependent: :destroy
  has_many :users, through: :badges_users

  validates :title, :image, :rule_name, :rule_value, presence: true
  validates :title, uniqueness: true
end

app/controllers/admin/badges_controller.rb
# frozen_string_literal: true

  class Admin::BadgesController < Admin::BaseController
    
    before_action :set_badge, only: %i[show edit update destroy]

    def index
      @badges = Badge.all
    end

    def show; end

    def new
      @badge = Badge.new
    end

    def edit; end

    def create
      @badge = current_user.badges.new(badge_params)

      if @badge.save
        redirect_to admin_badge_path(@badge), notice: t('.success')
      else
        render :new
      end
    end

    def update
      if @badge.update(badge_params)
        redirect_to admin_badge_path(@badge), notice: t('.success')
      else
        render :edit
      end
    end

    def destroy
      @badge.destroy

      redirect_to admin_badges_path, notice: t('.success')
    end

    private

    def set_badge
      @badge = Badge.find(params[:id])
    end

    def badge_params
      params.require(:badge).permit(:title, :image, :rule_name, :rule_value)
    end
  end

app/controllers/badges_controller.rb
# frozen_string_literal: true

class BadgesController < ApplicationController
  
  before_action :authenticate_user!

  def index
    @badges = Badge.all
    @user_badges = current_user.badges
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
  
<tr>
  <td class="align-middle"><%= badge.title %></td>
  <td class="align-middle"><%= image_tag badge.image, size: "90x90" %></td>
  <td class="align-middle"><%= badge.rule_name %></td>
  <td class="align-middle"><%= badge.rule_value %></td>
  <td class="align-middle"><%= link_to t('link_to_show'), admin_badge_path(badge) %> |</td>
  <td class="align-middle"><%= link_to t('link_to_edit'), edit_admin_badge_path(badge) %> |</td>
  <td class="align-middle">
    <%= link_to t('link_to_delete'), 
                admin_badge_path(badge),
                method: :delete,
                data: { confirm: t('confirm') } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :badge_title %>
  </p><br>

  <p>
    <%= form.label :image %><br>
    <%= form.text_field :image, id: :badge_image %>
  </p><br>

    <p>
    <%= form.label :rule_name %><br>
    <%= form.select :rule_name, Badge.badges_rules, { prompt: true } %>
  </p><br>

    <p>
    <%= form.label :rule_value %><br>
    <%= form.text_field :rule_value, id: :badge_rule_value %>
  </p><br>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/badges/edit.html.erb
<h1><%= t('.header', header: @badge.title) %></h1>

<%= render 'form' %>
<%= link_to t('link_to_back'), admin_badges_path %>

app/views/admin/badges/index.html.erb
<h1><%= t('.header') %></h1>

<p>
  <%= link_to t('link_to_new_badge'), new_admin_badge_path(@badge) %>
</p>

<%= render 'shared/errors', resource: @badge %>

<table class="table">
  <tr>
    <th><%= t('.title') %></th>
    <th><%= t('.image') %></th>
    <th><%= t('.rule_name') %></th>
    <th><%= t('.rule_value') %></th>
    <th colspan="3"><%= t('.actions') %></th> 
  </tr>

<%= render @badges %>
</table>

<%= link_to t('link_to_back'), admin_tests_path %>

app/views/admin/badges/new.html.erb
<h1><%= t('.header') %></h1>

<%= render 'form' %>
<%= link_to t('link_to_back'), admin_badges_path %>

app/views/admin/badges/show.html.erb
<p>
  <strong><%= t('.title', title: @badge.title) %></strong>
</p>

<p>
  <strong><%= t('.image', image: @badge.image) %></strong>
</p>

<p>
  <strong><%= t('.rule_name', rule_name: @badge.rule_name) %></strong>
</p>

<p>
  <strong><%= t('.rule_value', rule_value: @badge.rule_value) %></strong>
</p>

<%= link_to t('link_to_edit'), edit_admin_badge_path(@badge) %> 
<%= link_to t('link_to_back'), admin_badges_path %>