config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
  controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :users do
    resources :badges, only: %i[index]
    resources :feedbacks, only: %i[new create]
  end

  resources :tests_users, only: %i[show update] do
    resources :gists, only: :create
    member do
      get :attempt
    end
  end

  namespace :admin do
    resources :badges
    resources :gists, only: %i[index destroy]
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/admin.rb
class Admin < User
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  
  validate :validate_answer_count, on: :create

  scope :correct_answer, -> { where(correct: true) }

  private

  def validate_answer_count
    errors.add(:answers_count, 'Должно быть от 1-го до 4-х ответов!') if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
# frozen_string_literal: true

class Badge < ApplicationRecord

  enum badges_rules: {
    all_tests_by_category: 0,
    pass_test_by_level: 1,
    first_test_passed: 2
  }

  has_many :badges_users, dependent: :destroy
  has_many :users, through: :badges_users

  validates :title, :image, :rule_name, :rule_value, presence: true
  validates :title, uniqueness: true
end

app/models/badges_user.rb
# frozen_string_literal: true

class BadgesUser < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order('title') }
  
  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/feedback.rb
# frozen_string_literal: true

class Feedback < ApplicationRecord
  belongs_to :user

  validates :message, presence: true
end

app/models/gist.rb
# frozen_string_literal: true

class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :tests_users, dependent: :nullify, foreign_key: 'current_question_id'

  validates :body, presence: true
end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User'

  has_many :questions, dependent: :destroy
  has_many :tests_users, dependent: :destroy
  has_many :users, through: :tests_users

  validates :title, presence: true
  validates :title, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than: 0 }
  validates :timer, numericality: { only_integer: true, greater_than: 0, allow_nil: true }

  scope :easy_tests, -> { where(level: 0..1) }
  scope :mid_tests, -> { where(level: 2..4) }
  scope :hard_tests, -> { where(level: 5..Float::INFINITY) }
  scope :by_level, ->(level) { where(level: level) }
  scope :tests_by_category, -> (title_category) {
                                   joins(:category)
                                     .where(category: { title: title_category })
                                     .order(title: :desc)
                                 }

  def self.list_tests_by_category(title_category)
    tests_by_category(title_category).pluck(:title)
  end
end

app/models/tests_user.rb
# frozen_string_literal: true

class TestsUser < ApplicationRecord
  SUCCESS_RATIO = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question

  scope :success, -> { where(success: true) }

  def current_question_number
    test.questions.order(:id).where('id < ?', current_question.id).size + 1
  end

  def success_rate
    (100 / test.questions.count * result.to_f).round
  end

  def rate?
    success_rate >= SUCCESS_RATIO
  end

  def completed?
    current_question.nil? || time_is_up?
  end

  def time_is_up?
    test.timer.present? && time_left.negative?
  end
  
  def time_left
    created_at - Time.now + test.timer * 60
  end

  def accept!(answer_ids)
    self.result += 1 if correct_answer?(answer_ids)

    save!
  end

  def total_questions
    test.questions.count
  end

  def success_true
    update!(success: true)
  end

  private

  def before_validation_set_current_question
    self.current_question = next_question
  end

  def next_question
    if current_question.nil?
      test.questions.order(:id).first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    correct_answer.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answer
    current_question.answers.correct_answer
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable

  has_many :tests_users, dependent: :destroy
  has_many :tests, through: :tests_users
  has_many :badges_users, dependent: :destroy
  has_many :badges, through: :badges_users
  has_many :gists, dependent: :destroy
  has_many :author_tests, class_name: 'Test', foreign_key: :author_id, dependent: :destroy
  has_many :feedbacks, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true

  validates :email, presence: true
  validates :email, uniqueness: true, on: :create
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, on: :create

  def list_tests_by_level(level)
    tests.where(level: level)
  end

  def tests_user(test)
    tests_users.order(id: :desc).find_by(test_id: test.id)
  end
end

app/controllers/gists_controller.rb
# frozen_string_literal: true

class GistsController < ApplicationController
  before_action :authenticate_user!

  def create
    @tests_user = TestsUser.find(params[:tests_user_id])
    result = GistQuestionService.new(@tests_user.current_question).call

    if result.success?
      @gist = Gist.create!(gist_url: result.html_url, user: current_user, question: @tests_user.current_question)
      flash[:notice] = view_context.link_to(result.html_url, t('.success'))
    else
      flash[:alert] = t('.failure')
    end

    redirect_to @tests_user
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper

  CONTEXTUAL_ALERT_CSS_CLASS = { notice: 'alert alert-info', alert: 'alert alert-danger' }

  def current_year
    Date.current.year
  end

  def github_url(author, repo = nil)
    title = repo.nil? ? t('author', author: author).to_s : t('project', project: repo).to_s
    link_to title, "https://github.com/#{author}/#{repo}", target: '_blank'
  end

  def flash_class(key)
    CONTEXTUAL_ALERT_CSS_CLASS[key.to_sym]
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      t('new_question', new_question: question.test.title)
    else
      t('edit_question', edit_question: question.test.title)
    end
  end
end

app/helpers/tests_users_helper.rb
module TestsUsersHelper
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-dark bg-primary">
  <%= link_to 'Test Guru', root_path, class: 'navbar-brand' %>
  <div class="row text-center text-white">
    <%= t('.header') %>
  </div>
  <span class="navbar-text">
    <b><%= t('welcome', welcome: current_user.first_name) %></b> |
    <%= link_to t('badge'), admin_badges_path %> |
    <%= link_to t('admin_gists'), admin_gists_path %> |
    <%= link_to t('log_out'), destroy_user_session_path, method: :delete %>
  </span>
</nav>

app/views/shared/_errors.html.erb
  <% if resource.present? && resource.errors.any? %>
    <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
      <h2><%= t('.header', count: resource.errors.count) %>:</h2>

      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
  

app/views/shared/_flash_message.html.erb
<div class="row justify-content-center mt-3">
  <% flash.each do |key, msg| %>
    <div class="col col-md-4">
      <div class="text-center <%= flash_class(key) %>" role="alert" >
        <%= msg %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<h5><%= t('.header') %></h5>

<footer>
  <p><%= t('.current_year', count: current_year) %></p>
  <p><%= github_url('AlexanderG-v', 'TestGuru') %></p>
  <p><%= t('.description') %></p>
  <p><%= github_url('AlexanderG-v') %></p>
  <p><%= link_to t('link_to_thinknetika'), 'https://thinknetica.com/',target: '_blank' %></p>
</footer>

app/views/shared/_footer.ru.html.erb
<h5><%= t('.header') %></h5>

<footer>
  <p><%= t('.current_year', count: current_year) %></p>
  <p><%= github_url('AlexanderG-v', 'TestGuru') %></p>
  <p><%= t('.description') %></p>
  <p><%= github_url('AlexanderG-v') %></p>
  <p><%= link_to t('link_to_thinknetika'), 'https://thinknetica.com/',target: '_blank' %></p>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <%= link_to 'Test Guru', root_path, class: 'navbar-brand' %>
  <span class="navbar-text">
    <% if current_user.is_a?(Admin) %>
      <b><%= t('welcome', welcome: current_user.first_name) %></b> |
      <%= link_to t('admin_panel'), admin_tests_path %> |
      <%= link_to t('log_out'), destroy_user_session_path, method: :delete %>
    <% elsif user_signed_in? %>
      <b><%= t('welcome', welcome: current_user.first_name) %></b> |
      <%= link_to t('feedback'), new_user_feedback_path(current_user) %> |
      <%= link_to t('badge'), user_badges_path(current_user) %> |
      <%= link_to t('log_out'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('log_in'), new_session_path(resource_name) %> |
      <%= link_to t('sign_up'), new_registration_path(resource_name) %>
    <% end %>
  </span>
</nav>