config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
  controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :users do
    resources :badges, only: %i[index]
    resources :feedbacks, only: %i[new create]
  end

  resources :tests_users, only: %i[show update] do
    resources :gists, only: :create
    member do
      get :attempt
    end
  end

  namespace :admin do
    resources :badges
    resources :gists, only: %i[index destroy]
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/gist.rb
# frozen_string_literal: true

class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/admin/gists_controller.rb
# frozen_string_literal: true

class Admin::GistsController < Admin::BaseController
  def index
    @gists = Gist.all
  end

  def destroy
    @gist = Gist.find(params[:id])
    @gist.destroy!
    
    redirect_to admin_gists_path, notice: t('.success')
  end
end

app/controllers/gists_controller.rb
# frozen_string_literal: true

class GistsController < ApplicationController
  before_action :authenticate_user!

  def create
    @tests_user = TestsUser.find(params[:tests_user_id])
    result = GistQuestionService.new(@tests_user.current_question).call

    if result.success?
      @gist = Gist.create!(gist_url: result.html_url, user: current_user, question: @tests_user.current_question)
      flash[:notice] = view_context.link_to(result.html_url, t('.success'))
    else
      flash[:alert] = t('.failure')
    end

    redirect_to @tests_user
  end
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/admin/gists/_gist.html.erb
<div class="container mt-1">
  <div class="row ustify-content-md-center text-center">
    <div class=col-md-6><%= link_to gist.question.body.truncate(25), admin_question_path(gist.question) %></div>
    <div class=col-md><%= link_to gist.user, gist.gist_url, target: :_blank %></div>
    <div class=col-md><%= gist.user.email %></div>
    <div class=col-md><%= link_to t('link_to_delete'), admin_gist_path(gist),
                          method: :delete,
                          data: { confirm: t('confirm') } %>
    </div>
  </div>
</div>

app/views/admin/gists/index.html.erb
<div class="row text-center mt-3">
  <div class="col col-md-12">
    <h1><%= t('.header') %></h1>
  </div>
</div>
<div class="container mt-3">
  <div class="row ustify-content-md-center text-center" style="background-color: #e3f2fd;">
    <div class="col-md-6"><%= t('.questions') %></div>
    <div class=col-md><%= t('.gist_url') %></div>
    <div class=col-md><%= t('.user_email') %></div>
  </div>
</div>
<%= render @gists %>