config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
  controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :users do
    resources :badges, only: %i[index]
    resources :feedbacks, only: %i[new create]
  end

  resources :tests_users, only: %i[show update] do
    resources :gists, only: :create
    member do
      get :attempt
    end
  end

  namespace :admin do
    resources :badges
    resources :gists, only: %i[index destroy]
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :tests_users, dependent: :nullify, foreign_key: 'current_question_id'

  validates :body, presence: true
end

app/models/tests_user.rb
# frozen_string_literal: true

class TestsUser < ApplicationRecord
  SUCCESS_RATIO = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question

  scope :success, -> { where(success: true) }

  def current_question_number
    test.questions.order(:id).where('id < ?', current_question.id).size + 1
  end

  def success_rate
    (100 / test.questions.count * result.to_f).round
  end

  def rate?
    success_rate >= SUCCESS_RATIO
  end

  def completed?
    current_question.nil? || time_is_up?
  end

  def time_is_up?
    test.timer.present? && time_left.negative?
  end
  
  def time_left
    created_at - Time.now + test.timer * 60
  end

  def accept!(answer_ids)
    self.result += 1 if correct_answer?(answer_ids)

    save!
  end

  def total_questions
    test.questions.count
  end

  def success_true
    update!(success: true)
  end

  private

  def before_validation_set_current_question
    self.current_question = next_question
  end

  def next_question
    if current_question.nil?
      test.questions.order(:id).first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    correct_answer.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answer
    current_question.answers.correct_answer
  end
end

app/controllers/tests_users_controller.rb
# frozen_string_literal: true

class TestsUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tests_user, only: %i[show attempt update gist]

  def show; end

  def attempt; end

  def update
    @tests_user.accept!(params[:answer_ids])

    if @tests_user.completed?
      if @tests_user.rate?

        @tests_user.success_true
        badge_service = BadgeService.new(@tests_user).call
        flash[:notice] = t('.success') if badge_service.present?
      end

      TestsMailer.completed_test(@tests_user).deliver_now
      redirect_to attempt_tests_user_path(@tests_user)
    else
      render :show
    end
  end

  private

  def set_tests_user
    @tests_user = TestsUser.find(params[:id])
  end
end

app/helpers/tests_users_helper.rb
module TestsUsersHelper
end

app/views/tests_users/_progress.html.erb
<%= content_tag :div, 
                class: 'progress', 
                data: { current_number: @tests_user.current_question_number,
                        total_questions: @tests_user.total_questions } do %>
  
  <%= content_tag :div, class: 'progress-bar bg-info' do %>
  <% end %>
<% end %>

app/views/tests_users/attempt.html.erb
<h1><%= t('.header', header: @tests_user.test.title) %></h1>

<% if @tests_user.rate? %>
  <p><b style="color: #008000"> <%= t('.success', count: @tests_user.success_rate) %>%</b></p> 
<% else %>
  <p><b style="color: #FF0000"> <%= t('.failed', count: @tests_user.success_rate) %>%</b></p> 
<% end %>

<%= link_to t('link_to_back'), tests_path %>

app/views/tests_users/show.html.erb
<h1><%= t('.header', header: @tests_user.test.title) %></h1>

<b>
  <%= t('.total', count: @tests_user.test.questions.count) %>
</b><br>

<b>
  <%= t('.current', count: @tests_user.current_question_number)%>
</b><br>

<%= render 'progress' %>

<b>
  <%= t('.question', question: @tests_user.current_question.body) %>
</b>

<% if @tests_user.test.timer.present? %>
  <b data-time_start="<%= @tests_user.created_at %>",
    data-duration="<%= @tests_user.test.timer %>", class='timer'>
  </b>
<% end %>

<%= form_with url: tests_user_path(@tests_user), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @tests_user.current_question.answers, :id, :body, include_hidden:
  false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= link_to t('link_to_gist_question'), tests_user_gists_path(@tests_user), method: :post %></p>
  <p><%= form.submit t('.next'), class: "submit" %></p>
<% end %>